# The path to the (optional) KeyPass install folder
# settign this parameter will enable the option to use the keepass when prompted for the vault tokens
kps_path: ''
aws_s3_role: ''
aws_dynamo_role: ''

# Vault environments
# list the names and addressess of the vault environments you're using
vault_envs:
  Vault - DEV: 'http://my-dev-vault:8200'
#   Vault - QA: 'http://my-qa-vault:8200'
#   Vault - PROD: 'http://my-prod-vault:8200'
